build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.22
images:
- context_dir: .
  dockerfile_path: container/Dockerfile
  to: main
promotion:
  to:
  - name: qe-metrics
    namespace: qe-metrics
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: main
  org: RedHatQE
  repo: qe-metrics
  variant: image
