---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Published Images for RedHatQE/qe-metrics
    openshift.io/display-name: qe-metrics
  name: qe-metrics
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qe-metrics-image-puller-binding
  namespace: qe-metrics
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:image-puller
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
